//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessManagementService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Roles = new HashSet<Role>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string DepartmentName { get; set; }
        public string Phones { get; set; }
        public string Faxes { get; set; }
        public string Adress { get; set; }
        public string EmailAdress { get; set; }
        public string DeparetmentChartXML { get; set; }
        public string LogoPath { get; set; }
        public Nullable<bool> IsNeerdToConfirm { get; set; }
        public Nullable<bool> IsNeedConfirmToChangePassword { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public string Setting { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
