//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessManagementService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganiztionRole
    {
        public OrganiztionRole()
        {
            this.OrganiztionRole1 = new HashSet<OrganiztionRole>();
            this.Roles = new HashSet<Role>();
        }
    
        public int ID { get; set; }
        public string OrganizationRoleName { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<OrganiztionRole> OrganiztionRole1 { get; set; }
        public virtual OrganiztionRole OrganiztionRole2 { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
