//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessManagementService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public Right()
        {
            this.Groups = new HashSet<Group>();
            this.Roles = new HashSet<Role>();
        }
    
        public int ID { get; set; }
        public string RightName { get; set; }
        public string RelatedService { get; set; }
        public short RightType { get; set; }
        public string IsConfirmable { get; set; }
        public Nullable<int> OrganizationRoleID { get; set; }
        public Nullable<int> EntityID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
