//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessManagementService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Groups = new HashSet<Group>();
            this.Rights = new HashSet<Right>();
            this.Departments = new HashSet<Department>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OrganizationRoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<System.DateTime> LastRefreshTime { get; set; }
    
        public virtual OrganiztionRole OrganiztionRole { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Right> Rights { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
    }
}
